# Generated by Django 5.0.4 on 2024-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_gym_city_gym_locker_room_gym_music_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='city',
            field=models.CharField(choices=[('almaty', 'Алматы'), ('astana', 'Астана'), ('shymkent', 'Шымкент'), ('karaganda', 'Караганда'), ('oral', 'Орал')], default='almaty', max_length=100),
        ),
    ]
