# Generated by Django 5.0.4 on 2024-04-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_gym_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='image_url1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='image_url2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='image_url3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
