# Generated by Django 5.0.4 on 2024-04-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gym_image_url1_gym_image_url2_gym_image_url3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
