# Generated by Django 5.0.4 on 2024-04-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_gym_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='gym',
        ),
    ]
